### ISSUE TITLE
'System.AggregateException' occurred in Neo4j.Driver.dll 

### ISSUE THREAD

**Issue by SCKelemen** [neo4j-examples/movies-dotnet-bolt#3]
InnerException: {"The Neo4j Server doesn't support this client."}
StackTrace:    at Neo4j.Driver.Internal.Connector.SocketClient.<Start>d__9.MoveNext() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Connector\SocketClient.cs:line 61
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Neo4j.Driver.Internal.Connector.SocketConnection..ctor(ISocketClient socketClient, IAuthToken authToken, ILogger logger, IMessageResponseHandler messageResponseHandler) in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Connector\SocketConnection.cs:line 41
   at Neo4j.Driver.Internal.Connector.SocketConnection..ctor(Uri url, IAuthToken authToken, Config config) in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Connector\SocketConnection.cs:line 48
   at Neo4j.Driver.Internal.Session..ctor(Uri uri, IAuthToken authToken, Config config, IConnection conn, Action`1 releaseAction) in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Session.cs:line 40
   at Neo4j.Driver.Internal.SessionPool.<GetSession>b__13_0() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\SessionPool.cs:line 71
   at Neo4j.Driver.Internal.LoggerBase.TryExecute[T](Func`1 func) in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\LoggerBase.cs:line 54
   at Neo4j.Driver.Internal.SessionPool.GetSession() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\SessionPool.cs:line 60
   at Neo4j.Driver.Internal.Driver.Session() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Driver.cs:line 65
   at Neo4jDotNetDemo.Controllers.GraphController.Index(Int32 limit) in C:\Users\skelemen\Desktop\movies-dotnet-bolt-master\Neo4j.Driver.Example\Controllers\GraphController.cs:line 24
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

**Comment by SCKelemen** [comment]
Switched to using Neo4jClient.dll and it works fine.
